export const GET_ALL_RECIPE = 'GET_ALL_RECIPE';
export const SHEART_NAME_RECYPE = 'SHEART_NAME_RECYPE';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const GET_ALL_DIET = 'GET_ALL_DIET';
export const ORDER_BY_SCORE = 'ORDER_BY_SCORE';
export const PAGINADO = 'PAGINADO';
export const RECIPE_DETAILS = 'SRECIPE_DETAILS';
